# Generated by Django 4.1 on 2022-10-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='suggestion',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.AddField(
            model_name='feedback',
            name='mail_id',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
